/**
 * This code generated by CodeGenerator<ptma@163.com>
 */
package com.zz.zwj.service;

import java.util.Date;


/**
 * <p>实体类</p>
 * <p>Table: basic_app_config - 应用配置信息</p>
 *
 * @since 2017-02-16 06:07:20
 */
public class BasicAppConfigService {

    /** config_key - 配置键名称 */
    private String configKey;

    /** config_value - 配置值信息 */
    private String configValue;

    /** create_time - 添加日期 */
    private Date createTime;

    /** status - 状态 0为未启用 1为启用 */
    private Byte status;

    /** config_group - 配置组( 1：为用户启动项数据 ) */
    private Integer configGroup;

    /** remark - 备注 */
    private String remark;


    public String getConfigKey(){
        return this.configKey;
    }
    public void setConfigKey(String configKey){
        this.configKey = configKey;
    }

    public String getConfigValue(){
        return this.configValue;
    }
    public void setConfigValue(String configValue){
        this.configValue = configValue;
    }

    public Date getCreateTime(){
        return this.createTime;
    }
    public void setCreateTime(Date createTime){
        this.createTime = createTime;
    }

    public Byte getStatus(){
        return this.status;
    }
    public void setStatus(Byte status){
        this.status = status;
    }

    public Integer getConfigGroup(){
        return this.configGroup;
    }
    public void setConfigGroup(Integer configGroup){
        this.configGroup = configGroup;
    }

    public String getRemark(){
        return this.remark;
    }
    public void setRemark(String remark){
        this.remark = remark;
    }
}